[INFO] Identity service starting with issuer=identity-backend
[2025-08-02 17:24:29,371] ERROR in app: Exception on /login [GET]
Traceback (most recent call last):
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/auroraho/identity-backend/app.py", line 118, in login
    return render_template("login.html", error=error, next=next_url)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
[2025-08-02 17:24:30,710] ERROR in app: Exception on /login [GET]
Traceback (most recent call last):
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/auroraho/identity-backend/app.py", line 118, in login
    return render_template("login.html", error=error, next=next_url)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/auroraho/virtualenv/identity-backend/3.9/lib/python3.9/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
